[package]
name = "bnlcromdump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.6"
log = "0.4"
env_logger = "0.9.0"
steamlocate = "1.2"
native-dialog = "0.6"
